
import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { HeartHandshake, ShieldCheck, CheckCircle2, AlertTriangle, Download, Copy, Save, Upload, Lock } from 'lucide-react';
import './styles.css';

const STORAGE_KEY = 'pip-support-companion-v1';

const activities = [
  { id:'prep_food', section:'Daily Living', title:'Preparing food', question:'Can you prepare and cook a simple meal safely, reliably, repeatedly and in a reasonable time?', prompts:['Do you need an aid, adapted equipment, prompting, supervision or physical help?','Are there risks such as burns, cuts, falls, seizures, confusion, fatigue or forgetting food is cooking?','How often does this happen, and what happens on a bad day?'], options:[[0,'I can prepare and cook a simple meal unaided.'],[2,'I need an aid or appliance to prepare or cook a simple meal.'],[2,'I need prompting to prepare or cook a simple meal.'],[4,'I need supervision or assistance to prepare or cook a simple meal.'],[8,'I cannot prepare and cook food at all.']]},
  { id:'nutrition', section:'Daily Living', title:'Taking nutrition', question:'Can you eat and drink enough, including cutting food, using utensils, remembering to eat, or managing tube feeding if relevant?', prompts:['Do you need prompting because of low mood, anxiety, cognitive issues, eating disorder symptoms or forgetting?','Do you need food cut up, adapted cutlery, supervision, or help managing a therapeutic source?','Give examples of weight change, choking risk, missed meals, nausea, fatigue or pain.'], options:[[0,'I can take nutrition unaided.'],[2,'I need an aid, appliance, prompting, supervision or assistance to take nutrition.'],[4,'I need a therapeutic source to take nutrition.'],[6,'I need assistance to manage a therapeutic source.'],[10,'I cannot convey food and drink to my mouth and need another person to do so.']]},
  { id:'therapy', section:'Daily Living', title:'Managing therapy or monitoring a health condition', question:'Can you manage medication, treatment, therapy and monitoring without help?', prompts:['Do you forget doses, take the wrong dose, avoid treatment, or need reminders?','Does someone supervise or assist because of risk, side effects, dexterity, cognition or distress?','How many hours per week does therapy or monitoring take, including help from another person?'], options:[[0,'I can manage medication, therapy and monitoring unaided.'],[1,'I need an aid, appliance, supervision, prompting or assistance to manage medication or monitor my condition.'],[2,'I need help with therapy taking up to 3.5 hours a week.'],[4,'I need help with therapy taking more than 3.5 but no more than 7 hours a week.'],[6,'I need help with therapy taking more than 7 but no more than 14 hours a week.'],[8,'I need help with therapy taking more than 14 hours a week.']]},
  { id:'washing', section:'Daily Living', title:'Washing and bathing', question:'Can you wash and bathe yourself safely and completely?', prompts:['Do you need aids, grab rails, a shower seat, prompting, supervision or physical help?','Can you get in and out of a bath or shower? Can you wash hair, lower body, back or between shoulders and waist?','Describe pain, falls, fatigue, breathlessness, panic, skin issues or how long it takes.'], options:[[0,'I can wash and bathe unaided.'],[2,'I need an aid, appliance, prompting, supervision or assistance for some washing or bathing.'],[3,'I need assistance to get in or out of a bath or shower.'],[4,'I need assistance to wash my body between shoulders and waist.'],[8,'I cannot wash and bathe at all and need another person to wash my whole body.']]},
  { id:'toilet', section:'Daily Living', title:'Managing toilet needs or incontinence', question:'Can you manage toilet needs or incontinence hygienically and safely?', prompts:['Do you need aids, adapted clothing, prompting, help transferring, cleaning, changing pads or managing accidents?','How often do accidents happen? Do you avoid going out because of this?','Describe infections, skin soreness, falls, urgency, bowel or bladder symptoms.'], options:[[0,'I can manage toilet needs or incontinence unaided.'],[2,'I need an aid, appliance or prompting to manage toilet needs or incontinence.'],[4,'I need assistance to manage toilet needs.'],[6,'I need assistance to manage incontinence of either bladder or bowel.'],[8,'I need assistance to manage incontinence of both bladder and bowel.']]},
  { id:'dressing', section:'Daily Living', title:'Dressing and undressing', question:'Can you dress and undress appropriately, safely and in a reasonable time?', prompts:['Do you need aids, adapted clothes, prompting, help choosing suitable clothes, or physical help?','Can you manage fastenings, socks, shoes, bras, compression garments or upper-body clothing?','Explain pain, fatigue, dexterity, balance, sensory issues, cognition or mental health barriers.'], options:[[0,'I can dress and undress unaided.'],[2,'I need an aid, appliance, prompting or assistance with either upper or lower body clothing.'],[4,'I need assistance with both upper and lower body clothing.'],[8,'I cannot dress or undress at all.']]},
  { id:'communication', section:'Daily Living', title:'Communicating verbally', question:'Can you express and understand spoken information?', prompts:['Do you need a communication aid, interpreter, familiar person, prompting or support?','Are complex conversations harder than basic ones?','Give examples such as appointments, phone calls, panic, speech, hearing, processing or understanding.'], options:[[0,'I can express and understand verbal information unaided.'],[2,'I need a communication aid or appliance.'],[4,'I need support to express or understand complex verbal information.'],[8,'I need support to express or understand basic verbal information.'],[12,'I cannot express or understand verbal information at all.']]},
  { id:'reading', section:'Daily Living', title:'Reading and understanding', question:'Can you read and understand signs, symbols and written information?', prompts:['Do you need glasses beyond normal correction, magnification, screen readers, prompting or another person?','Can you understand bills, letters, medical instructions, warnings and appointment information?','Describe vision, literacy, cognitive, learning, concentration or mental health difficulties.'], options:[[0,'I can read and understand basic and complex written information unaided.'],[2,'I need an aid, appliance or prompting to read or understand written information.'],[4,'I need another person to help me understand complex written information.'],[8,'I need another person to help me understand basic written information, or I cannot read signs, symbols or words at all.']]},
  { id:'engaging', section:'Daily Living', title:'Engaging with other people face to face', question:'Can you engage with other people face to face appropriately and without overwhelming distress?', prompts:['Do you need prompting or social support from someone trained or experienced in helping you?','What happens with strangers, authority figures, groups, appointments or conflict?','Describe anxiety, panic, shutdowns, aggression, confusion, risk or recovery time afterwards.'], options:[[0,'I can engage with other people unaided.'],[2,'I need prompting to engage with other people.'],[4,'I need social support to engage with other people.'],[8,'I cannot engage with other people because it causes overwhelming psychological distress.']]},
  { id:'budgeting', section:'Daily Living', title:'Making budgeting decisions', question:'Can you make simple and complex budgeting decisions?', prompts:['Can you understand bills, change, bank accounts, direct debits, contracts or debt?','Do you need prompting, supervision or someone else to manage money because of risk?','Describe impulsivity, confusion, exploitation, low mood, addiction, learning difficulty or memory problems.'], options:[[0,'I can make complex budgeting decisions unaided.'],[2,'I need prompting or assistance to make complex budgeting decisions.'],[4,'I need prompting or assistance to make simple budgeting decisions.'],[6,'I cannot make any budgeting decisions at all.']]},
  { id:'journeys', section:'Mobility', title:'Planning and following journeys', question:'Can you plan and follow journeys safely and reliably?', prompts:['Can you plan a route, leave home, cope with unfamiliar or familiar journeys, and recover afterwards?','Do you need prompting, a support person, route training, taxis, familiar routes or avoidance strategies?','Describe anxiety, panic, cognitive problems, sensory overload, seizures, disorientation or risk.'], options:[[0,'I can plan and follow journeys unaided.'],[4,'I need prompting to undertake any journey to avoid overwhelming psychological distress.'],[8,'I cannot plan the route of a journey.'],[10,'I cannot follow the route of an unfamiliar journey without another person, assistance dog or orientation aid.'],[10,'I cannot undertake any journey because it would cause overwhelming psychological distress.'],[12,'I cannot follow the route of a familiar journey without another person, assistance dog or orientation aid.']]},
  { id:'moving', section:'Mobility', title:'Moving around', question:'How far can you stand and then move safely, repeatedly, to an acceptable standard and in a reasonable time?', prompts:['Think about the distance you can do more than once, not a one-off best effort.','Include aids, pain, breathlessness, fatigue, falls, balance, recovery time and whether you must stop.','Estimate real distances: rooms, driveway, bus stop, shop aisle, GP surgery, car park.'], options:[[0,'I can stand and move more than 200 metres.'],[4,'I can stand and move more than 50 metres but no more than 200 metres.'],[8,'I can stand and move unaided more than 20 metres but no more than 50 metres.'],[10,'I can stand and move using an aid or appliance more than 20 metres but no more than 50 metres.'],[12,'I can stand and move more than 1 metre but no more than 20 metres, either aided or unaided.'],[12,'I cannot stand or cannot move more than 1 metre.']]}
];
const evidenceTypes = ['GP, consultant or specialist letters','Medication list and side effects','Care plan, support worker notes or carer statement','Therapy, counselling, physio or OT reports','Hospital discharge letters or appointment records','Photographs of aids, adaptations or injuries','Diary entries showing good and bad days','Receipts or records for taxis, delivery, equipment or support'];
const emptyAnswers = Object.fromEntries(activities.map(a => [a.id, { optionIndex: 0, examples: '', frequency: '', aids: '', evidence: '' }]));
const defaultState = { claimant: { name: '', condition: '', date: new Date().toISOString().slice(0,10) }, answers: emptyAnswers, diary: [], evidence: Object.fromEntries(evidenceTypes.map(e => [e,false])), ethicsAccepted: false };
function loadState(){ try { return JSON.parse(localStorage.getItem(STORAGE_KEY)) || defaultState; } catch { return defaultState; } }
function pointsLabel(p){ return p === 1 ? '1 point' : `${p} points`; }
function safe(t){ return (t||'').trim() || 'Not yet recorded.'; }
function totals(answers){ return activities.reduce((acc,a)=>{ acc[a.section] += a.options[answers[a.id]?.optionIndex || 0][0]; return acc; }, {'Daily Living':0, Mobility:0}); }
function rate(p){ return p >= 12 ? 'enhanced-rate threshold' : p >= 8 ? 'standard-rate threshold' : 'below threshold'; }
function App(){
 const [data,setData]=useState(loadState); const [tab,setTab]=useState('start'); const [selected,setSelected]=useState(activities[0].id); const [newDiary,setNewDiary]=useState({date:new Date().toISOString().slice(0,10),dayType:'Mixed',note:''});
 useEffect(()=>localStorage.setItem(STORAGE_KEY,JSON.stringify(data)),[data]);
 const t=useMemo(()=>totals(data.answers),[data.answers]); const activity=activities.find(a=>a.id===selected)||activities[0]; const answer=data.answers[activity.id]||emptyAnswers[activity.id];
 const updateAnswer=(field,value)=>setData(d=>({...d, answers:{...d.answers, [activity.id]:{...answer,[field]:value}}}));
 const summary=useMemo(()=>{
  const lines=[]; lines.push('PIP Support Companion draft summary'); lines.push(`Claimant: ${safe(data.claimant.name)}`); lines.push(`Main conditions or difficulties: ${safe(data.claimant.condition)}`); lines.push(`Prepared on: ${data.claimant.date}`); lines.push(''); lines.push('Important: claimant-reviewed draft. Check for accuracy before using. Not legal advice.'); lines.push(''); lines.push(`Indicative Daily Living points selected: ${t['Daily Living']} (${rate(t['Daily Living'])})`); lines.push(`Indicative Mobility points selected: ${t.Mobility} (${rate(t.Mobility)})`); lines.push('');
  activities.forEach(a=>{ const ans=data.answers[a.id]||emptyAnswers[a.id]; const choice=a.options[ans.optionIndex||0]; lines.push(`${a.section}: ${a.title}`); lines.push(`Selected statement: ${choice[1]} (${pointsLabel(choice[0])})`); lines.push(`How often / reliability: ${safe(ans.frequency)}`); lines.push(`Aids, prompting, supervision or assistance: ${safe(ans.aids)}`); lines.push(`Real examples: ${safe(ans.examples)}`); lines.push(`Supporting evidence: ${safe(ans.evidence)}`); lines.push(''); });
  const ev=Object.entries(data.evidence).filter(([,v])=>v).map(([k])=>k); lines.push('Evidence gathered or planned:'); lines.push(ev.length?ev.map(x=>`- ${x}`).join('\n'):'- Not yet recorded.'); lines.push(''); lines.push('Diary notes:'); lines.push(data.diary.length?data.diary.map(e=>`- ${e.date} (${e.dayType}): ${e.note}`).join('\n'):'- No diary entries yet.'); return lines.join('\n');
 },[data,t]);
 const copy=()=>navigator.clipboard.writeText(summary); const download=()=>{ const blob=new Blob([summary],{type:'text/plain'}); const url=URL.createObjectURL(blob); const a=document.createElement('a'); a.href=url; a.download=`pip-draft-summary-${data.claimant.name||'claimant'}.txt`; a.click(); URL.revokeObjectURL(url); };
 return <div className="page"><header className="hero"><div><div className="brand"><span className="logo"><HeartHandshake/></span><div><h1>PIP Support Companion</h1><p>Describe difficulties honestly, clearly and accurately.</p></div></div><p className="intro">This is NOT the official PIP application form. It is a guided tool for recording real examples, checking PIP activities, collecting evidence and producing a draft summary for claimant review.</p></div><div className="guard"><ShieldCheck/><b>Ethical guardrails</b><p>Use real examples. Do not understate difficulties. Do not exaggerate.</p></div></header>
 <nav>{['start','activities','diary','evidence','summary'].map(x=><button key={x} onClick={()=>setTab(x)} className={tab===x?'active':''}>{x[0].toUpperCase()+x.slice(1)}</button>)}</nav>
 {tab==='start'&&<main className="grid"><section className="card wide"><h2>Applicant start page</h2><p>Before answering, confirm that this tool is for accurate self-reporting only.</p><label className="notice"><input type="checkbox" checked={data.ethicsAccepted} onChange={e=>setData({...data,ethicsAccepted:e.target.checked})}/> I will answer honestly using real examples. I understand this is not legal advice and I should review everything before using it.</label><label>Name<input value={data.claimant.name} onChange={e=>setData({...data,claimant:{...data.claimant,name:e.target.value}})} placeholder="Applicant name"/></label><label>Date<input type="date" value={data.claimant.date} onChange={e=>setData({...data,claimant:{...data.claimant,date:e.target.value}})}/></label><label>Conditions, impairments or main difficulties<textarea value={data.claimant.condition} onChange={e=>setData({...data,claimant:{...data.claimant,condition:e.target.value}})} placeholder="For example: pain, fatigue, anxiety, seizures, cognitive issues, mobility problems..."/></label><button disabled={!data.ethicsAccepted} onClick={()=>setTab('activities')}>Begin activities</button></section><section className="card"><h3>Reliability prompts</h3>{['Can you do it safely, without risk of harm?','Can you do it to an acceptable standard?','Can you do it repeatedly, as often as reasonably required?','Can you do it in a reasonable time?','Does this apply on more than half of days over time?'].map(p=><p className="tick" key={p}><CheckCircle2/> {p}</p>)}</section></main>}
 {tab==='activities'&&<main className="layout"><aside className="card"><h2>Activities</h2><p className="pill">{t['Daily Living']} Daily Living / {t.Mobility} Mobility</p>{activities.map(a=>{const pts=a.options[data.answers[a.id]?.optionIndex||0][0];return <button className={`activity ${selected===a.id?'selected':''}`} onClick={()=>setSelected(a.id)} key={a.id}><b>{a.title}</b><span>{a.section} · {pointsLabel(pts)}</span></button>})}</aside><section className="card"><p className="pill">{activity.section}</p><h2>{activity.title}</h2><p>{activity.question}</p><div className="warning"><AlertTriangle/> Do not answer based only on your best day. Consider safety, repetition, time taken, pain, fatigue, distress, prompting, supervision and help from another person.</div><div className="prompts">{activity.prompts.map(p=><p key={p}>{p}</p>)}</div><label>Which statement is closest?<select value={answer.optionIndex||0} onChange={e=>updateAnswer('optionIndex',Number(e.target.value))}>{activity.options.map(([pts,label],i)=><option value={i} key={label}>{pointsLabel(pts)} — {label}</option>)}</select></label><div className="two"><label>How often does this happen?<textarea value={answer.frequency} onChange={e=>updateAnswer('frequency',e.target.value)} placeholder="Include good, bad and typical days."/></label><label>Aids, prompting, supervision or assistance<textarea value={answer.aids} onChange={e=>updateAnswer('aids',e.target.value)} placeholder="Who helps? What equipment? What would happen without help?"/></label><label>Real examples<textarea value={answer.examples} onChange={e=>updateAnswer('examples',e.target.value)} placeholder="Describe a recent incident: what happened, where, help needed and consequence."/></label><label>Supporting evidence<textarea value={answer.evidence} onChange={e=>updateAnswer('evidence',e.target.value)} placeholder="Letters, diary entries, care notes, photos, prescriptions, witness examples..."/></label></div></section></main>}
 {tab==='diary'&&<main className="grid"><section className="card"><h2>Difficulties diary</h2><input type="date" value={newDiary.date} onChange={e=>setNewDiary({...newDiary,date:e.target.value})}/><select value={newDiary.dayType} onChange={e=>setNewDiary({...newDiary,dayType:e.target.value})}><option>Good</option><option>Mixed</option><option>Bad</option><option>Very bad</option></select><textarea value={newDiary.note} onChange={e=>setNewDiary({...newDiary,note:e.target.value})} placeholder="What happened today? Which activity was affected? How long did it take? What help was needed?"/><button onClick={()=>{if(!newDiary.note.trim())return; setData({...data,diary:[{...newDiary,id:Date.now()},...data.diary]}); setNewDiary({date:new Date().toISOString().slice(0,10),dayType:'Mixed',note:''});}}><Save/> Save diary entry</button></section><section className="card"><h3>Saved entries</h3>{data.diary.length===0?<p>No diary entries yet.</p>:data.diary.map(e=><div className="entry" key={e.id}><b>{e.date} · {e.dayType}</b><p>{e.note}</p></div>)}</section></main>}
 {tab==='evidence'&&<main className="card"><h2>Evidence checklist</h2><p>Tick evidence that exists or should be requested.</p><div className="evidence">{evidenceTypes.map(item=><label key={item}><input type="checkbox" checked={!!data.evidence[item]} onChange={e=>setData({...data,evidence:{...data.evidence,[item]:e.target.checked}})}/><Upload/> {item}</label>)}</div></main>}
 {tab==='summary'&&<main className="grid"><section className="card"><h2>Indicative result</h2><div className="score"><span>Daily Living</span><b>{t['Daily Living']}</b><em>{rate(t['Daily Living'])}</em></div><div className="score"><span>Mobility</span><b>{t.Mobility}</b><em>{rate(t.Mobility)}</em></div><p className="notice"><Lock/> This prototype stores answers only in this browser's local storage.</p></section><section className="card wide"><h2>Draft claimant summary</h2><button onClick={copy}><Copy/> Copy</button><button onClick={download}><Download/> Download</button><pre>{summary}</pre></section></main>}
 <footer>Prototype MVP. Not affiliated with DWP. Not legal advice. Applicant must review before use.</footer></div>
}
createRoot(document.getElementById('root')).render(<App/>);
